[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "grist-api>=0.1.1",
    "logging>=0.4.9.6",
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "pytest>=9.0.1",
]
